version: '3.8'

services: 
  db:
    image: postgres:latest
    container_name: 'api-postgres'
    environment:
      POSTGRES_DB: 'donor_db'
      POSTGRES_USER: 'admin'
      POSTGRES_PASSWORD: 'password'
      POSGRES_HOST_AUTH_METHOD: 'trust'
    volumes:
      - db_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432

volumes:
  db_data:
    driver: local