// <auto-generated />
using System;
using DonorApi.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DonorApi.Migrations
{
    [DbContext(typeof(DonorDbContext))]
    [Migration("20220503030217_AddPledgeAndStatus")]
    partial class AddPledgeAndStatus
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DonorApi.Models.Designation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DonorId")
                        .HasColumnType("integer")
                        .HasColumnName("donor_id");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("label");

                    b.HasKey("Id");

                    b.HasIndex("DonorId");

                    b.ToTable("designation", "data");
                });

            modelBuilder.Entity("DonorApi.Models.Donor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CurrentDriveStatus")
                        .HasColumnType("integer")
                        .HasColumnName("current_drive_status");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("phone_number");

                    b.HasKey("Id");

                    b.ToTable("donors", "data");
                });

            modelBuilder.Entity("DonorApi.Models.Pledge", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Amount")
                        .HasColumnType("integer")
                        .HasColumnName("amount");

                    b.Property<DateTimeOffset>("Date")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date");

                    b.Property<int>("DonorId")
                        .HasColumnType("integer")
                        .HasColumnName("donor_id");

                    b.HasKey("Id");

                    b.HasIndex("DonorId");

                    b.ToTable("pledges", "data");
                });

            modelBuilder.Entity("DonorApi.Models.Designation", b =>
                {
                    b.HasOne("DonorApi.Models.Donor", "Donor")
                        .WithMany("Designations")
                        .HasForeignKey("DonorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Donor");
                });

            modelBuilder.Entity("DonorApi.Models.Pledge", b =>
                {
                    b.HasOne("DonorApi.Models.Donor", "Donor")
                        .WithMany("Pledges")
                        .HasForeignKey("DonorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Donor");
                });

            modelBuilder.Entity("DonorApi.Models.Donor", b =>
                {
                    b.Navigation("Designations");

                    b.Navigation("Pledges");
                });
#pragma warning restore 612, 618
        }
    }
}
